added services css and html (responsive)
front-end-by-rimantas/18-grupe-portfolio-martin pull request #35
Opened 2020-10-12 14:12 UTC by Ukanotas

kol kas dar negeneruojama su js, viskas tik html'e ir css.

2020-10-12 15:02 UTC, belauzas requested changes

2020-10-12 15:02 UTC, belauzas commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
Palikime lokalią font-awesome.css versiją

2020-10-12 18:10 UTC, Ukanotas commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
> Palikime lokalią font-awesome.css versiją

ten nera visu reikiamu ikonu :/ bet ok

2020-10-13 05:29 UTC, BrigitaK commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
O gal gali pridėti ne font-awesome.min.css, o tą pilną?

2020-10-13 05:52 UTC, SkajaQ commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
Beje, as lokalios irgi niekad nenaudoju, nes man kazkodel vietoj ikonu tik tuscius kvadratelius piesia.. Su Nagliu viska isieskojom, neradom problemos.. tad gal galima visgi naudoti kai ka kitko?
@belauzas

2020-10-13 07:45 UTC, BrigitaK commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
O idedi ir font folderi?

2020-10-13 07:46 UTC, BrigitaK commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
Nes Naglis kazkada bande daryti, bet ne viskas buvo sukelta.

2020-10-13 08:38 UTC, SkajaQ commented on index.html
> +    <script src="https://kit.fontawesome.com/aab904dbe0.js" crossorigin="anonymous"></script>
Taip, zinoma

2020-10-13 11:25 UTC, closed without merging